Integration Test: L2 fetch task
madara-alliance/madara pull request #253
Opened 2024-09-10 10:26 UTC by Mohiiit

Integration test for the l2 fetch task
# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Testing

## What is the current behavior?

Resolves: #NA

## Does this introduce a breaking change?

No

2024-09-11 07:16 UTC, apoorvsadana commented on CHANGELOG.md
do we undo the madara <-> deoxys changes?

2024-09-11 07:16 UTC, apoorvsadana commented on crates/client/sync/src/fetch/fetchers.rs
> +    println!("Checkpoint 1: Starting fetch_block_and_updates for block {}", block_n);
let's make the `println!` as `log::trace!`

2024-09-11 07:16 UTC, apoorvsadana commented on crates/client/sync/src/fetch/fetchers.rs
> +    println!("Checkpoint 1: Starting fetch_class_updates");
should we make the log more verbose? like `FCU Checkpoint` and `FBU Checkpoint` etc.

2024-09-11 07:16 UTC, apoorvsadana commented on crates/client/sync/src/fetch/fetchers.rs
> +    println!("Checkpoint A: Starting fetch_class for class_hash {}", class_hash);
A -> 1, so that it's coherent with above :)

2024-09-11 07:16 UTC, apoorvsadana commented on crates/client/sync/src/tests/utils/class_hash.json
rename to class instead of class_hash? and maybe add to an artifacts folder?

2024-09-11 07:16 UTC, apoorvsadana commented on crates/client/sync/src/tests/utils/gateway.rs
> +    pub fn mock_class_hash(&self) {
since this a generic util, maybe we can take the file path as an arg?

2024-09-11 07:16 UTC, apoorvsadana commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert!(matches!(pending_block, UnverifiedPendingFullBlock { .. }));
i think we can skip the assert! above and directly do `Ok(Some(UnverifiedPendingFullBlock { .. }))`

2024-09-11 07:16 UTC, apoorvsadana commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert!(pending_block.header.parent_block_hash.is_some(), "Parent block hash should be present");
should we directly compare with expected block hash?

2024-09-11 07:16 UTC, apoorvsadana commented on crates/client/sync/src/fetch/fetchers.rs
> +        match result.unwrap_err() {
we can directly do `assert_matches!` for the error

2024-09-11 07:16 UTC, apoorvsadana commented on crates/client/sync/src/fetch/fetchers.rs
> +        match result.unwrap_err() {
same as above

2024-09-11 07:16 UTC, apoorvsadana commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert!(!class_updates.is_empty(), "Should have fetched at least one class update");
instead of asserts before unwraps, i think we can just do `.expects` directly and make the code smaller :)

2024-09-11 07:16 UTC, apoorvsadana commented on crates/client/sync/src/fetch/mod.rs
> +                    println!("Received block {}", expected_block_number);
println! -> log::debug?

2024-09-11 07:16 UTC, apoorvsadana commented on crates/client/sync/src/fetch/mod.rs
> +    async fn test_basic_functionality() {
can combine all to one test case

2024-09-11 08:00 UTC, Mohiiit commented on CHANGELOG.md
yes, my bad, it's back

2024-09-11 08:00 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +    println!("Checkpoint 1: Starting fetch_block_and_updates for block {}", block_n);
removed, it was checkpoint for debugging

2024-09-11 08:01 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +    println!("Checkpoint 1: Starting fetch_class_updates");
removed, it was checkpoint for debugging

2024-09-11 08:01 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +    println!("Checkpoint A: Starting fetch_class for class_hash {}", class_hash);
removed, it was checkpoint for debugging

2024-09-11 08:01 UTC, Mohiiit commented on crates/client/sync/src/tests/utils/class_hash.json
resolved

2024-09-11 08:01 UTC, Mohiiit commented on crates/client/sync/src/tests/utils/gateway.rs
> +    pub fn mock_class_hash(&self) {
done

2024-09-11 08:01 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert!(matches!(pending_block, UnverifiedPendingFullBlock { .. }));
resolved

2024-09-11 08:01 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert!(pending_block.header.parent_block_hash.is_some(), "Parent block hash should be present");
done

2024-09-11 08:01 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +        match result.unwrap_err() {
resolved

2024-09-11 08:01 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +        match result.unwrap_err() {
done

2024-09-11 08:02 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert!(!class_updates.is_empty(), "Should have fetched at least one class update");
resolved

2024-09-11 08:02 UTC, Mohiiit commented on crates/client/sync/src/fetch/mod.rs
> +                    println!("Received block {}", expected_block_number);
removed

2024-09-11 08:02 UTC, Mohiiit commented on crates/client/sync/src/fetch/mod.rs
> +    async fn test_basic_functionality() {
done

2024-09-18 07:04 UTC, jbcaron commented on CHANGELOG.md
> +- tests: integration test for l2 fetch task added
Make sure to add the changelog entry at the top of the file to ensure the latest changes are listed first

2024-09-18 07:04 UTC, jbcaron commented on crates/client/sync/src/tests/utils/artifacts/class.json
Is the choice of this class arbitrary?

2024-09-18 07:59 UTC, Mohiiit commented on crates/client/sync/src/tests/utils/artifacts/class.json
yes, just for testing, when we are mocking the feeder gateway for the class response

2024-09-18 09:08 UTC, jbcaron commented on crates/client/sync/src/tests/utils/artifacts/class.json
why not compile a light test contract like in the `client/devnet` crate so as not to have such big artifacts?

2024-09-18 10:50 UTC, Mohiiit commented on CHANGELOG.md
> +- tests: integration test for l2 fetch task added
resolved

2024-09-18 11:06 UTC, Mohiiit commented on crates/client/sync/src/tests/utils/artifacts/class.json
while mocking, I was getting `data did not match any variant of enum GatewayResponse` and hence used the class hash directly

2024-09-18 11:06 UTC, Mohiiit commented on crates/client/sync/src/tests/utils/artifacts/class.json
looking into it tho, in case it can be sorted out

2024-09-18 12:46 UTC, Mohiiit commented on crates/client/sync/src/tests/utils/artifacts/class.json
somehow, when I am compiling the contracts I am not getting the response that I am getting from the feeder gateway, so I am not sure is there any other way to mock the response

2024-09-19 07:04 UTC, Trantorian1 requested changes
Check comments below.

A lot of tests seems flaky in that they do not check for the actual mocked values, making it possible for some interior mutations to be left uncaught. Hopefully they would be caught in some other tests, but it feels strange that we are not asserting for very specific data given we have absolute control over our mocks.

2024-09-19 07:04 UTC, Trantorian1 commented on crates/client/sync/src/fetch/fetchers.rs
> +    async fn test_fetch_pending_block_and_updates_not_found(test_setup: Arc<MadaraBackend>) {
Hasn't this behavior changed since #258 ?

2024-09-19 07:04 UTC, Trantorian1 commented on crates/client/sync/src/tests/utils/gateway.rs
> +    pub fn mock_block_pending_not_found(&self) {
Is this still possible after #258 ?

2024-09-19 07:04 UTC, Trantorian1 commented on crates/client/sync/src/tests/utils/gateway.rs
> +    pub fn mock_block_pending_internal_error(&self) {
Same here

2024-09-19 07:04 UTC, Trantorian1 commented on crates/client/sync/src/fetch/fetchers.rs
> +                Err(ref e) if matches!(
What is this code here for?

2024-09-19 07:04 UTC, Trantorian1 commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert!(!state_update.state_diff.storage_diffs.is_empty(), "State update should contain storage diffs");
Given we are mocking the entire state update, shouldn't this be a bit more specific with the actual expected values?

2024-09-19 07:04 UTC, Trantorian1 commented on crates/client/sync/src/fetch/fetchers.rs
> +            state_update.state_diff.deployed_contracts.is_empty(),
Same here

2024-09-19 07:04 UTC, Trantorian1 commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert!(block.block_hash.is_some(), "Block should have a hash");
In general, why not expect the mocked data? This does not feel very robust

2024-09-19 07:04 UTC, Trantorian1 commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert_ne!(pending_block.header.l1_gas_price.eth_l1_gas_price, 0, "ETH L1 gas price should not be zero");
Since we are mocking the entire pending block this should be set to the actual mocked value

2024-09-19 07:04 UTC, Trantorian1 commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert!(
Same, why not check against the actual state diff?

2024-09-19 09:35 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +    async fn test_fetch_pending_block_and_updates_not_found(test_setup: Arc<MadaraBackend>) {
if I am not wrong, that was for internal fetching, like when we are fetching from the db, here we are testing with the feeder gateway response

2024-09-19 09:40 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +                Err(ref e) if matches!(
firstly we are checking that if it's error or not, and then given the `fetch_class_updated` returns the `L2SyncError` we are checking that it's the `ClassHashNotFound` error inside

2024-09-19 09:43 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert!(
resolved

2024-09-19 09:43 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert_ne!(pending_block.header.l1_gas_price.eth_l1_gas_price, 0, "ETH L1 gas price should not be zero");
resolved

2024-09-19 09:43 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert!(block.block_hash.is_some(), "Block should have a hash");
resolved

2024-09-19 09:43 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +            state_update.state_diff.deployed_contracts.is_empty(),
resolved

2024-09-19 09:43 UTC, Mohiiit commented on crates/client/sync/src/fetch/fetchers.rs
> +        assert!(!state_update.state_diff.storage_diffs.is_empty(), "State update should contain storage diffs");
resolved

2024-09-19 11:04 UTC, Mohiiit commented on crates/client/sync/src/tests/utils/artifacts/class.json
resolved

2024-09-19 11:25 UTC, jbcaron commented on crates/client/sync/src/fetch/mod.rs
> +        ctx.mock_class_hash("cairo/target/dev/madara_contracts_TestContract.contract_class.json");
great

2024-09-19 11:34 UTC, Trantorian1 approved these changes

2024-09-19 11:37 UTC, jbcaron approved these changes

2024-09-19 12:06 UTC, Mohiiit commented on crates/client/sync/src/fetch/mod.rs
> +        ctx.mock_class_hash("cairo/target/dev/madara_contracts_TestContract.contract_class.json");
good idea indeed, thanks

2024-09-19 12:10 UTC, merged