fix : events from call info / UDC cairo 0 migration
madara-alliance/madara pull request #263
Opened 2024-09-14 07:33 UTC by ocdbytes

- Events emitting fix.
- UDC migration to cairo 0. (to support starknet.js `deploy` function)

2024-09-17 07:26 UTC, apoorvsadana commented on crates/primitives/receipt/src/from_blockifier.rs
> +    fn call_info() -> CallInfo {
does this work (AI generated)


```rust
fn create_call_info(event_number: u32, inner_calls: Vec<CallInfo>) -> CallInfo {
    CallInfo {
        call: Default::default(),
        execution: execution(vec![ordered_event(event_number)]),
        resources: Default::default(),
        inner_calls,
        storage_read_values: vec![],
        accessed_storage_keys: Default::default(),
    }
}

let nested_calls = vec![
    create_call_info(1, vec![
        create_call_info(2, vec![
            create_call_info(3, vec![
                create_call_info(4, vec![])
            ])
        ])
    ])
];
```

2024-09-18 13:26 UTC, Mohiiit commented on crates/primitives/receipt/src/from_blockifier.rs
> +    fn call_info() -> CallInfo {
resolved

2024-09-18 14:58 UTC, apoorvsadana approved these changes

2024-09-20 07:27 UTC, Trantorian1 requested changes
All seems good, just please update your use of the `log` crate to refer to workspace dependencies.

2024-09-20 07:27 UTC, Trantorian1 commented on crates/primitives/receipt/Cargo.toml
> +log = "0.4.21"
Please use workspace log

2024-09-22 12:44 UTC, EvolveArt approved these changes

2024-09-22 15:42 UTC, Mohiiit commented on crates/primitives/receipt/Cargo.toml
> +log = "0.4.21"
resolved

2024-09-23 06:38 UTC, Trantorian1 approved these changes

2024-09-23 06:41 UTC, merged