feat: Reorg Support (WIP)
madara-alliance/madara pull request #296
Opened 2024-10-01 23:09 UTC by notlesh

This PR adds basic support for reorgs.

This is a WIP. Currently a minimal unit test has been added for a basic reorg, and I believe I have identified where in the import pipeline it is appropriate to handle a reorg (please review this!)

# Pull Request type

Feature

## What is the current behavior?

I expect reorgs would be dropped because a block's parent_header is checked against the tip of the chain and an error is produced if the two don't match.

Resolves: #202 

## What is the new behavior?

TODO:

## Does this introduce a breaking change?

TODO:

2025-03-21 21:17 UTC, notlesh commented on madara/crates/client/block_import/src/verify_apply.rs
> +fn reorg(
Thoughts on calling this `reorg()`?

It's really just reverting. Other than some test cases, there is no actual reorg going on.

It might help to have some clear distinction between the two, so I'll define it here (let me know if you disagree):

* `Revert`: Set the current tip of the blockchain to some direct ancestor, dropping all blocks in between
* `Reorg`: Set the current tip of the blockchain to a block on another fork of the blockchain. Achieved by first reverting to the most recent common ancestor, then applying new blocks until the desired one is reached.

With this distinction in mind, I think this should be called revert and that this current PR isn't so much about reorgs (again, other than the tests).

2025-03-21 21:20 UTC, notlesh commented on madara/crates/client/block_import/src/verify_apply.rs
> +        .ok_or(BlockImportError::Internal(Cow::Owned("no latest block after reorg".to_string())))?;
Thoughts on this -- esp. whether it's an issue and how to prevent it?

2025-03-21 21:25 UTC, notlesh commented on madara/crates/client/db/src/block_db.rs
> +        tx.put_cf(&meta, ROW_SYNC_TIP, latest_block_n_encoded);
We set the `ROW_SYNC_TIP` here, but do we need to do anything else related to the tip of the chain? Anything with pending blocks?

2025-03-21 21:27 UTC, notlesh reviewed
I think the current `fn reorg()` belongs somewhere else. Originally it was in `verify_apply.rs` because it was intended to *detect* reorgs during block import, but that is no longer the case. Any thoughts on where would be more appropriate?

2025-03-25 10:07 UTC, whichqua commented on madara/crates/client/block_import/src/verify_apply.rs
> +) -> Result<ReorgResult, BlockImportError> {
I think `Result<ReorgResult, ..>` is a little confusing. Maybe rename `ReorgResult` to `ReorgData`?

2025-03-25 11:14 UTC, whichqua commented on madara/crates/client/block_import/src/verify_apply.rs
> +    new_tip: &PreValidatedBlock, // TODO: we don't need a PreValidatedBlock, do we?
Seems like you are using new tip to get the block_number and block_hash maybe you should let the caller handle that?

2025-03-25 11:55 UTC, raynaudoe commented on madara/crates/client/block_import/src/verify_apply.rs
> +        .ok_or(BlockImportError::Internal(Cow::Owned("no latest block after reorg".to_string())))?;
maybe using a lock for the entire reorg fn and any insert attempt should check that lock?
I think the scenario where a pending block is being inserted while a reorg happens is possible 🤔

2025-03-25 14:07 UTC, notlesh commented on madara/crates/client/block_import/src/verify_apply.rs
> +) -> Result<ReorgResult, BlockImportError> {
Agreed, I was trying to be consistent with other structs defined in `types.rs` but `ReorgData` is less ambiguous and consistent with the RPC spec.

2025-03-25 14:11 UTC, notlesh commented on madara/crates/client/block_import/src/verify_apply.rs
> +        .ok_or(BlockImportError::Internal(Cow::Owned("no latest block after reorg".to_string())))?;
Yes, I think it needs some sort of locking mechanism, but I want to make sure I reuse something that exists for this purpose rather than create my own :)

2025-03-25 15:11 UTC, notlesh commented on madara/crates/client/block_import/src/verify_apply.rs
> +) -> Result<ReorgResult, BlockImportError> {
Changed in [4ec928a](https://github.com/madara-alliance/madara/pull/296/commits/4ec928ac6e1550756b3d9a66d10153f1865ffcd6)

2025-03-25 15:56 UTC, notlesh commented on madara/crates/client/block_import/src/verify_apply.rs
> +    new_tip: &PreValidatedBlock, // TODO: we don't need a PreValidatedBlock, do we?
Cleaned this up in [0b44e12](https://github.com/madara-alliance/madara/pull/296/commits/0b44e12a06c2fdcd68a6cb306da3ab78044d7276):

* reorg only wants a hash now
* we look up block number from hash, which implicitly ensures the block exists in our db
* cleaned up the test code a bit

2025-04-01 09:41 UTC, cchudant requested changes

2025-04-01 09:41 UTC, cchudant commented on madara/crates/client/block_import/src/types.rs
> +    pub starting_block_hash: Felt,
why do we need block hashes here?
i think if you're just modifying the backend, you should probably just have a revert_to(block_n: u64) function in the backend, it would be the responsability of sync to catch a reorg.

Well, unless you're making a broadcast channel in the backend to listen to reorgs - but i thought you were still working on the database reverting part.

2025-04-01 09:41 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
> +fn reorg(
should go into the backend imo, and be called revert_to

2025-04-01 09:41 UTC, cchudant commented on madara/crates/client/db/src/storage_updates.rs
> +        self.block_db_revert(revert_to)
reverting block_db is not sufficient, but I think you're aware of it as we talked about it before
(sorry if this pr was supposed to be a draft)

2025-04-03 19:06 UTC, notlesh commented on madara/crates/client/block_import/src/types.rs
> +    pub starting_block_hash: Felt,
The link above explains why -- it's to prepare for the reorg subscription RPC.

But it also gives more information than just block number, I'd rather provide as much context as possible to the caller.

It's also used in tests IIRC.

2025-04-03 19:08 UTC, notlesh commented on madara/crates/client/db/src/storage_updates.rs
> +        self.block_db_revert(revert_to)
Can you elaborate? We also need to revert the bonsai tries, but that's done elsewhere. Is that what you mean?

2025-04-04 18:42 UTC, notlesh commented on madara/crates/client/db/src/storage_updates.rs
> +        self.block_db_revert(revert_to)
[d8b045f](https://github.com/madara-alliance/madara/pull/296/commits/d8b045f221e069a29b06c2b1ec6c7efa2a5fa364) adds support for removing declared class info and rolls back contract state. It's not optimized but should suffice for small reorgs, or at least for early testing :)

2025-04-07 17:41 UTC, notlesh commented
> should go into the backend imo, and be called revert_to

I tried moving this to `mc_db` but I don't think it really fits there because it's doing a lot with the bonsai trie, and the backend doesn't touch bonsai tries much (even though they are accessed through `MadaraBackend`).

The current reorg logic (which, yes, should be renamed to `revert`) still seems pretty closely tied with all all of the logic in `verify_apply.rs`, it's basically the opposite of `verify_apply_inner()`:

* it cares about the current block hash/num (similar to the `check_parent_hash_and_num()` call)
* it reverts trie updates (opposite of the `update_tries()` call)
* it reverts db state (opposite of `backend.store_block()` call)

In addition, testing it the way I've done so far relies on building a blockchain by calls to `verify_apply_inner()`.

Let me know if I'm still thinking about this the wrong way.

(CC @cchudant)

2025-04-09 16:06 UTC, cchudant requested changes
one quick test that I would really love to see is a very dumb test that tries to import some blocks, then revert all of them and at that point the db should be completely empty

this would make sure we're not missing anything that should be reverted

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/block_production/src/lib.rs
> +#[cfg(any(test, feature = "testing"))]
why here?

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/db/src/block_db.rs
>          for block_n in (revert_to + 1..latest_block_n + 1).rev() {
(revert_to + 1..=latest_block_n).rev()

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/db/src/block_db.rs
> +            let state_diff_serialized = self.db.get_cf(&block_n_to_state_diff, block_n_encoded.clone())?.unwrap(); // TODO: unwrap, should we expect an entry for every single block here, or will some
yes, but we should put make a MadaraStorageError IMO instead of panicking

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/db/src/block_db.rs
> +            let state_diff_serialized = self.db.get_cf(&block_n_to_state_diff, block_n_encoded.clone())?.unwrap(); // TODO: unwrap, should we expect an entry for every single block here, or will some
to make it consistent with how we deal with errors everywhere else in mc-db

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/db/src/class_db.rs
> +    pub(crate) fn classes_db_revert(
class_db_revert to make it consistent with the other methods IMO?

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/db/src/class_db.rs
> +        let mut deprecated_declared_class_hashes = HashSet::new();
why 3 for loops and intermediary hashset?

just loop through the `state_diffs` param and insert to the write batch as you go no?

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/db/src/contract_db.rs
> +        let mut contract_storage_keys = HashSet::new();
ditto, i dont think these are necessary this can be simplified, just go through the input vec and push stuff into the change batch

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/db/src/contract_db.rs
> +        for block_n in (revert_to + 1..latest_block_n + 1).rev() {
..=

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/block_production/src/lib.rs
> +#[cfg(any(test, feature = "testing"))]
ah you moved it
idk if it should stay here if you're using from another crate, this feels messy

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
> +            format!("no block found for requested tip {}", new_tip_block_hash).to_string(),
format! returns a String, the to_string here is unnecessary

also, please use ok_or_else if you're using format! in the else branch, the cost of fomat! and allocation shouldnt be paid for when taking the non-erroring path

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
> +            format!("no block found for requested tip {}", new_tip_block_hash).to_string(),
```rs
.ok_or_else(|| BlockImportError::Internal(format!("no block found for requested tip {new_tip_block_hash:#x}").into()))
```
into is handy for Cow

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
> +            format!("no block found for requested tip {}", new_tip_block_hash).to_string(),
also, notice the :#x
when formatting felts, you need the :#x otherwise it will be formatted as a decimal number instead of hexadecimal and it's very ugly
(starknet-types-core's fault)

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
> +        previous_tip_block_info.block_n().expect("Previous tip block must have a block number");
to make it consistent with the rest of the codebase, it would be great to remove the expect and return errors
(not saying this was a great choice to begin with, maybe all of those internal errors should be using .expect() but the ship has already been sailed and i would prefer it to be consistent)

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
same here, ok_or should be a ok_or_else and idk why you're using to_string on a litteral to put that into a Cow::Owned, you can just make a Cow::Borrowed


or use into, which does the Cow for you
.ok_or_else(|| BlockImportError::Internal("no latest block after reorg".into()))?;

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
(same for the rest of the pr)

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
>      // TODO: ensure there is no race condition here...? (e.g. we reverted and someone else appends a block before this next call)
this is the caller's responsability. it'll be much more clear when sync-refactor pr is merged, as i wrote an extensive doc on this subject

but to be brief, i would say this is either: block_production's responsability - and it's very easy for it to ensure it is not doing anything silly
or, mc-sync when we're running sync instead of block production.

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
>          ending_block_hash: latest_block_info.block_hash().expect("how would a block not have a hash?"), // TODO: better error message, but srsly, how?
latest_block_info returns a "maybe pending block", because you can also ask for the pending block. The pending block has no block_hash as it's not closed yet. This is because there's a concept of a "pending block" in starknet.

You can cast the MadaraMaybePendingBlockInfo using .as_nonpending().

the MadaraBackend right now is a bit silly regarding that, you can't query a "closed block" (meaning, non-pending) without having to deal with the fact that you might have asked for a pending one - ideally we would have a get_closed_block_info taking a block_n: u64, or a kind of block tag that excludes pending blocks.

i really want to refactor the MadaraBackend at some point because it's full of dumb stuff like that (which is why you have to deal with soo many error cases right now)

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
>          ending_block_hash: latest_block_info.block_hash().expect("how would a block not have a hash?"), // TODO: better error message, but srsly, how?
```rs
let block_info = backend
  .get_block_info(&BlockId::Tag(BlockTag::Latest))
  .map_err(make_db_error("getting latest block info"))?
  .ok_or(BlockImportError::Internal("No latest block after reorg".into()))?;
let block_info = block_info.as_nonpending()
  .ok_or(BlockImportError::Internal("Asked for a closed block; got a pending one".into()))?;
// and then you can just have `block_info.block_hash` which is a `Felt`.
```

2025-04-09 16:06 UTC, cchudant commented on madara/crates/client/db/src/storage_updates.rs
>      pub fn revert_to(&self, revert_to: u64) -> Result<(), MadaraStorageError> {
you also need to clear the pending block here

2025-04-09 16:08 UTC, cchudant commented
(my review is not final i probably missed some stuff, i'll continue tomorrow I think)

2025-04-09 16:23 UTC, cchudant requested changes

2025-04-09 16:23 UTC, cchudant commented on madara/crates/client/db/src/contract_db.rs
> +    // TODO: does this need rayon thread pool? what about #[tracing::instrument()] ?
i don't know about tracing::instrument - currently it's sprinkled without much thought in the codebase and we don't really have a clear rule. We should probably ask @heemankv what the rule should be to be honest.

2025-04-09 16:23 UTC, cchudant commented on madara/crates/client/db/src/contract_db.rs
> +    // TODO: does this need rayon thread pool? what about #[tracing::instrument()] ?
does this need rayon thread pool? => right now I don't think you're using anything that uses rayon, so you don't really need to put that comment.

context:
the reason the use of rayon is documented on top of the storage updates functions is that when calling a rayon function from the tokio pool, it'll block the tokio pool and probably starve the worker threads, which is suboptimal.
We use rayon functions (par_iter, etc) for storage update functions because it allows us to offload compute-heavy stuff into a pool that's made for it ; and rayon has a very very low parallelization overhead (but can only be used for compute-heavy stuff) - all of this without starving the tokio workers which ar for IO stuff.

It's the caller responsability to make sure it's not calling a function that uses rayon stuff from the tokio pool.
Tokio pool handles IO stuff and is where async/.await can be used.

Tokio has a section explaining what I mean: https://docs.rs/tokio/latest/tokio/#cpu-bound-tasks-and-blocking-code

2025-04-09 16:23 UTC, cchudant commented on madara/crates/client/db/src/contract_db.rs
> +            // TODO: we may be able to leverage RocksDb's tree-based iterator here to avoid looping over each block
true!

2025-04-09 16:35 UTC, cchudant commented
> > should go into the backend imo, and be called revert_to
> 
> I tried moving this to `mc_db` but I don't think it really fits there because it's doing a lot with the bonsai trie, and the backend doesn't touch bonsai tries much (even though they are accessed through `MadaraBackend`).
> 
> The current reorg logic (which, yes, should be renamed to `revert`) still seems pretty closely tied with all all of the logic in `verify_apply.rs`, it's basically the opposite of `verify_apply_inner()`:
> 
>     * it cares about the current block hash/num (similar to the `check_parent_hash_and_num()` call)
> 
>     * it reverts trie updates (opposite of the `update_tries()` call)
> 
>     * it reverts db state (opposite of `backend.store_block()` call)
> 
> 
> In addition, testing it the way I've done so far relies on building a blockchain by calls to `verify_apply_inner()`.
> 
> Let me know if I'm still thinking about this the wrong way.
> 
> (CC @cchudant)

i think it's fine for now yes

2025-04-09 17:14 UTC, notlesh commented on madara/crates/client/block_production/src/lib.rs
> +#[cfg(any(test, feature = "testing"))]
Yeah, seems messy. I'm up for suggestions

2025-04-09 17:15 UTC, notlesh commented
> one quick test that I would really love to see is a very dumb test that tries to import some blocks, then revert all of them and at that point the db should be completely empty
> 
> this would make sure we're not missing anything that should be reverted

The tests do that, but an explicit check to ensure there is no state whatsoever is a good idea. This would work for both the db and bonsai tries...

2025-04-09 19:38 UTC, notlesh commented on madara/crates/client/db/src/contract_db.rs
> +        for block_n in (revert_to + 1..latest_block_n + 1).rev() {
[1b9a023](https://github.com/madara-alliance/madara/pull/296/commits/1b9a023d212f021cbdde8fb59627ed0c31f66dff)

2025-04-09 19:38 UTC, notlesh commented on madara/crates/client/db/src/block_db.rs
>          for block_n in (revert_to + 1..latest_block_n + 1).rev() {
[1b9a023](https://github.com/madara-alliance/madara/pull/296/commits/1b9a023d212f021cbdde8fb59627ed0c31f66dff)

2025-04-09 19:38 UTC, notlesh commented on madara/crates/client/db/src/class_db.rs
> +    pub(crate) fn classes_db_revert(
[702aee5](https://github.com/madara-alliance/madara/pull/296/commits/702aee5f2cccdd94c5e0f037dfebd43cb3776a9d)

2025-04-09 19:42 UTC, notlesh commented on madara/crates/client/db/src/class_db.rs
> +        let mut deprecated_declared_class_hashes = HashSet::new();
Good catch, this case can be simplified (done in [91ec01c](https://github.com/madara-alliance/madara/pull/296/commits/91ec01c0a5b3f69c69d085e5def75b536f262331)).

The `HashMap`s were used to dedupe things, but that's not relevant for declared classes since that can only happen once.

Note that the similar case in `contract_db.rs` is still a relevant optimization, see below.

2025-04-09 19:45 UTC, notlesh commented on madara/crates/client/db/src/contract_db.rs
> +        let mut contract_storage_keys = HashSet::new();
This is an optimization to dedupe things. However, without the RocksDb tree iterator optimization it's actually creating more work..! Good catch, I'll go ahead and work on adding it.

2025-04-09 21:46 UTC, notlesh commented on madara/crates/client/db/src/contract_db.rs
> +        let mut contract_storage_keys = HashSet::new();
I started to implement this and realized it isn't necessarily an optimization -- it would probably perform worse in most cases. It might perform better in cases where a value is changed a lot (e.g. storage items in a popular dex).

Given that, I'd prefer the simplest approach, and so I ripped out the dedupe code as you suggested.

This leaves some caveats, namely that some important things aren't validated:
* `StateDiff`s passed to `contract_db_revert` need a corresponding block number, and there's no way to enforce this
* The diffs should be contiguous and end on the current blockchain tip
* `RocksDb` doesn't appear to give you any way to know if something was deleted or how many things were deleted, which would otherwise be a great/simple/low-overhead sanity check to ensure the revert code is removing the exact items it expects

`*_db_revert()` fns are all `pub(crate)` and are documented with these caveats at least.

See [cd27f22](https://github.com/madara-alliance/madara/pull/296/commits/cd27f2203d8d15688eb8ac2e08393890b70e3968)

2025-04-09 22:08 UTC, notlesh commented on madara/crates/client/block_import/src/verify_apply.rs
>      // TODO: ensure there is no race condition here...? (e.g. we reverted and someone else appends a block before this next call)
Ok, thanks for clarifying. Is there anything about this I should mention in the fn documentation, or is this obvious enough?

2025-04-09 22:12 UTC, notlesh commented on madara/crates/client/block_import/src/verify_apply.rs
> +            format!("no block found for requested tip {}", new_tip_block_hash).to_string(),
Good points, thanks. I believe `clippy` can handle some of this, it would be good to add to CI...

[e33d5b9](https://github.com/madara-alliance/madara/pull/296/commits/e33d5b90867e5ee6980a11706afe4098db2b0355)

2025-04-09 22:13 UTC, notlesh commented on madara/crates/client/block_import/src/verify_apply.rs
> +        previous_tip_block_info.block_n().expect("Previous tip block must have a block number");
[e33d5b9](https://github.com/madara-alliance/madara/pull/296/commits/e33d5b90867e5ee6980a11706afe4098db2b0355)

2025-04-09 22:16 UTC, notlesh commented on madara/crates/client/block_import/src/verify_apply.rs
[e33d5b9](https://github.com/madara-alliance/madara/pull/296/commits/e33d5b90867e5ee6980a11706afe4098db2b0355) and [e17319b](https://github.com/madara-alliance/madara/pull/296/commits/e17319baa14f6a99baaea0e4e8ae82515cde57bc)

2025-04-09 22:44 UTC, notlesh commented on madara/crates/client/block_import/src/verify_apply.rs
>          ending_block_hash: latest_block_info.block_hash().expect("how would a block not have a hash?"), // TODO: better error message, but srsly, how?
Ah, this gives some good context, thanks.

One problem: the non-pending block doesn't have a block number :laughing: 

```rust
pub struct MadaraBlockInfo {
    pub header: Header,
    pub block_hash: Felt,
    pub tx_hashes: Vec<Felt>,
}
```

2025-04-09 22:49 UTC, notlesh commented on madara/crates/client/block_import/src/verify_apply.rs
>          ending_block_hash: latest_block_info.block_hash().expect("how would a block not have a hash?"), // TODO: better error message, but srsly, how?
Ah, thanks, this actually gives me a lot of good context. Cleaned this up more in [807f040](https://github.com/madara-alliance/madara/pull/296/commits/807f040131a17455a3845823878a3d6a598c919c)

2025-04-09 22:51 UTC, notlesh commented on madara/crates/client/db/src/block_db.rs
> +            let state_diff_serialized = self.db.get_cf(&block_n_to_state_diff, block_n_encoded.clone())?.unwrap(); // TODO: unwrap, should we expect an entry for every single block here, or will some
[807f040](https://github.com/madara-alliance/madara/pull/296/commits/807f040131a17455a3845823878a3d6a598c919c)

2025-04-10 08:45 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
>      // TODO: ensure there is no race condition here...? (e.g. we reverted and someone else appends a block before this next call)
it was obvious to me, but maybe adding a quick "caller should ensure noone is saving or reverting any block while this function is running" can be good
(although, store_block & cie also have the same problem and it's not documented)

2025-04-10 08:54 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
> +        .ok_or_else(|| BlockImportError::Internal(Cow::Borrowed("on blockchain tip in storage")))?;
BlockImportError::Internal("There are no blocks in the database".into())

2025-04-10 08:54 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
> +        .ok_or_else(|| BlockImportError::Internal(Cow::Borrowed("on blockchain tip in storage")))?;
oh by the way, on starknet the genesis block is block 0 and is executable
we import it and is mostly treated like any other block

when doing `.get_block_info(&BlockId::Tag(BlockTag::Latest))` it can indeed return None, if the genesis block has not been imported yet

(in that case, means there is no latest block in db, and get_latest_block_n is None)

2025-04-10 08:54 UTC, cchudant commented on madara/crates/client/block_import/src/verify_apply.rs
> +        .ok_or_else(|| BlockImportError::Internal(Cow::Borrowed("Previous tip block must have a block number")))?;
nit: Cow Borrowed can be replaced with .into() on the litteral

2025-04-10 08:54 UTC, cchudant commented on madara/crates/client/db/src/block_db.rs
> +                    MadaraStorageError::InconsistentStorage(Cow::Owned(format!("Block {block_n} has no StateDiff")))
nit: Cow::Owned can be replaced with .into() on the result of format!

2025-04-10 08:54 UTC, cchudant commented on madara/crates/client/db/src/storage_updates.rs
>      pub fn revert_to(&self, revert_to: u64) -> Result<(), MadaraStorageError> {
self.clear_pending_block() iirc

2025-04-10 09:03 UTC, cchudant requested changes
clearing the pending block is the only remaining issue I think, the rest is mostly style nitpicks

2025-04-10 09:03 UTC, cchudant commented on madara/crates/client/block_production/Cargo.toml
> +rstest = { workspace = true, optional = true }
this needs to be in dev-dependencies

2025-04-10 09:03 UTC, cchudant commented on madara/crates/client/block_production/src/lib.rs
> +#[cfg(any(test, feature = "testing"))]
it would make more sense in block import but i dont really have a strong opinion, it's probably fine

2025-04-10 09:03 UTC, cchudant commented on madara/crates/client/db/src/block_db.rs
> +        tx.put_cf(&meta, ROW_SYNC_TIP, latest_block_n_encoded);
IIRC no

2025-04-10 09:03 UTC, cchudant commented on madara/crates/client/db/src/block_db.rs
> +        tx.delete_cf(&meta, ROW_PENDING_STATE_UPDATE);
we also need to clear the pending block in classdb and blockdb, but I think it's just easier to remove the clearing of pending block from here and just call the .clear_pending_block() fn in the main db revert_to() function

2025-04-10 14:51 UTC, notlesh commented on madara/crates/client/block_import/src/verify_apply.rs
> +        .ok_or_else(|| BlockImportError::Internal(Cow::Borrowed("on blockchain tip in storage")))?;
[f080b5c](https://github.com/madara-alliance/madara/pull/296/commits/f080b5c08b130542ecdc42cbfadaaef8dd32f2ae)

2025-04-10 15:01 UTC, notlesh commented on madara/crates/client/db/src/storage_updates.rs
>      pub fn revert_to(&self, revert_to: u64) -> Result<(), MadaraStorageError> {
[7518bc7](https://github.com/madara-alliance/madara/pull/296/commits/7518bc7d7dce70a51929cd4d7c1ac80732ef8026)

2025-04-10 15:01 UTC, notlesh commented on madara/crates/client/db/src/storage_updates.rs
>      pub fn revert_to(&self, revert_to: u64) -> Result<(), MadaraStorageError> {
A bit off topic, but why do we store pending blocks in the db? A pending block is just a block that is being built, right? Why not keep it in RAM until it's become a proper block?

2025-04-10 15:39 UTC, notlesh commented on madara/crates/client/db/src/block_db.rs
> +        tx.delete_cf(&meta, ROW_PENDING_STATE_UPDATE);
Removed this (since `clear_pending_block()` is being called now) and added some clarification about it in [6b49010](https://github.com/madara-alliance/madara/pull/296/commits/6b4901044efe1d400b6a48a5bbfc2b31812479d7)

2025-04-10 16:29 UTC, notlesh commented on madara/crates/client/block_production/Cargo.toml
> +rstest = { workspace = true, optional = true }
I ended up just copying the fixtures that I needed in [9b0e528](https://github.com/madara-alliance/madara/pull/296/commits/9b0e528788bfe1776091dec56852b36b862b0c59). I couldn't find a clean way to share them across crates with just `#[cfg(test)]` so I figured this was the lesser of two evils.

2025-04-10 20:40 UTC, notlesh commented
> one quick test that I would really love to see is a very dumb test that tries to import some blocks, then revert all of them and at that point the db should be completely empty

This was a great idea. I applied it to the `bonsai-trie`s and discovered [this bug](https://github.com/madara-alliance/bonsai-trie/issues/42).

I tried applying it to the `RocksDb`s, but it doesn't appear that there's easy ways to do things like query the number of items stored. Of course, this can be done, but it may be tedious / inefficient (e.g. iterate through each key by prefix `''`). Let me know if you have suggestions on this.

2025-04-15 10:33 UTC, cchudant approved these changes
cool!

2025-04-15 10:33 UTC, cchudant commented on madara/crates/client/db/src/storage_updates.rs
>      pub fn revert_to(&self, revert_to: u64) -> Result<(), MadaraStorageError> {
because we want to be able to keep the pending block around across restarts

I have a PR that will be up soon that replaces the db reads to the pending block to read into RAM, meaning db will only be involved when the pending block changes and needs to be saved again

2025-07-14 10:11 UTC, closed without merging