replacing the reqwest feeder client with hyper
madara-alliance/madara pull request #357
Opened 2024-10-22 19:02 UTC by jbcaron

# Pull Request type

- Refactoring (no functional changes, no API changes)

## What is the current behavior?

Resolves: #NA

## What is the new behavior?

- 

## Does this introduce a breaking change?

No

## Other information

2024-10-24 07:53 UTC, Trantorian1 requested changes

2024-10-24 07:53 UTC, Trantorian1 commented on crates/client/gateway/src/client/builder.rs
> +impl Policy<Request<String>, Response<Incoming>, Box<dyn Error + Send + Sync>> for RetryPolicy {
Consider updating the code to make it more evident this is a retry policy (there also exists `tower::hedge::Policy`)

```suggestion
impl retry::Policy<Request<String>, Response<Incoming>, Box<dyn Error + Send + Sync>> for RetryPolicy {
```

2024-10-24 07:53 UTC, Trantorian1 commented on crates/client/gateway/src/client/builder.rs
> +                if response.status().as_u16() == 429 {
Consider using `http::StatusCode::TOO_MANY_REQUESTS` instead.

```suggestion
                if response.status() == http::StatusCode::TOO_MANY_REQUESTS {
```

2024-10-24 07:53 UTC, Trantorian1 commented on crates/client/gateway/src/client/builder.rs
> +}
This seems counter-productive: what is the point of rate limiting if the request can pass a `Rety-After` header with a duration of 0s? Imo we should default all requests to a retry duration of 10s.

2024-10-24 07:53 UTC, Trantorian1 commented on crates/client/gateway/src/client/builder.rs
> +                    Some(Box::pin(fut))
Consider using `futures::future::FutureExt` instead. This is more of a nitpick and requires adding
```toml
futures = { workspace = true, features = ["thread-pool"] }
```
to this crates `cargo.toml`.

```suggestion
                    let fut = async move {
                        let mut pause_lock = pause_until.write().await;
                        *pause_lock = Some(Instant::now() + retry_after);

                        // wait for the retry_after duration
                        tokio::time::sleep(retry_after).await;

                        next_policy
                    }.boxed();
                    Some(fut)
```

2024-10-24 07:53 UTC, Trantorian1 commented on crates/client/gateway/src/client/builder.rs
> +                }))
Same here.

2024-10-24 07:53 UTC, Trantorian1 commented on crates/client/gateway/src/client/builder.rs
> +        Box::pin(fut)
Same

2024-10-24 07:53 UTC, Trantorian1 commented on crates/client/gateway/src/client/request_builder.rs
> +        let mut req_builder = Request::builder().method("GET").uri(uri);
Consider using `http::Method::GET` instead.
```suggestion
        let mut req_builder = Request::builder().method(http::Method::GET.as_str()).uri(uri);
```

2024-10-24 07:53 UTC, Trantorian1 commented on crates/client/gateway/src/client/request_builder.rs
> +        }
Something like this should be more performant:
```rust
req_builder.headers_mut().unwrap().extend(self.headers);
```

2024-10-24 07:53 UTC, Trantorian1 commented on crates/client/gateway/src/client/request_builder.rs
> +        let mut req_builder = Request::builder().method("POST").uri(uri);
Consider using `http::Method::POST` instead.
```suggestion
        let mut req_builder = Request::builder().method(http::Method::POST.as_str()).uri(uri);
```

2024-10-24 07:53 UTC, Trantorian1 commented on crates/client/gateway/src/client/request_builder.rs
>          }
Same here

2024-10-24 07:53 UTC, Trantorian1 commented on crates/client/gateway/src/client/request_builder.rs
> +    let whole_body = response.collect().await.unwrap().aggregate();
Replace this `unwrap` by an `expect`

2024-10-24 08:04 UTC, Trantorian1 commented
Please also consider adding back a message signifying that rate limiting has occurred as it just seems like Madara is unresponsive atm.

2024-10-24 08:05 UTC, Trantorian1 commented
Also there seems to be some difficulties with `Ctrl-C`ing out of Madara when the node sleeps due to rate limiting.

2024-10-24 10:19 UTC, jbcaron commented on crates/client/gateway/src/client/builder.rs
> +}
yes we can define a minimum, after verification the sequencer does not send this header

2024-10-25 05:04 UTC, jbcaron commented
> Also there seems to be some difficulties with `Ctrl-C`ing out of Madara when the node sleeps due to rate limiting.

fix

2024-10-25 07:07 UTC, Trantorian1 approved these changes
All good!

2024-10-25 09:54 UTC, closed without merging