fix(fgw): include `l1_to_l2_consumed_message` in L1 handler receipt
madara-alliance/madara pull request #381
Opened 2024-11-13 15:31 UTC by jbcaron

## Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix

## What is the current behavior?

the `l1_to_l2_consumed_message` field is missing in the FGW receipt

Resolves: #375 

## What is the new behavior?

retrieve the `l1_to_l2_consumed_message` directly from the L1 handler transaction

## Does this introduce a breaking change?

No

## Other information

**⚠️ merge #380 before**

2024-11-18 08:33 UTC, Trantorian1 requested changes
Seems good, small fix for `felt_to_h160`.

2024-11-18 08:33 UTC, Trantorian1 commented on crates/primitives/convert/src/felt.rs
> +    if !bytes.iter().take(12).all(|&b| b == 0) {
Why not a simple comparison of the type `felt > 2^160 - 1` (pseudocode) with a static `from_hex_unchecked` ?

2024-11-18 08:33 UTC, Trantorian1 commented on crates/primitives/convert/src/lib.rs
> +pub use felt::{felt_to_h160, felt_to_u128, felt_to_u64};
This should be merged after #380

2024-11-18 10:43 UTC, cchudant approved these changes
how did we miss that when comparing what the starkware fgw and ours returns?

2024-11-18 10:44 UTC, jbcaron commented on crates/primitives/convert/src/felt.rs
> +    if !bytes.iter().take(12).all(|&b| b == 0) {
checking the first 12 bytes for nulls directly aligns with the H160 conversion logic, ensuring clarity and structural validation, whereas a numeric comparison obscures this intent

2024-11-18 10:50 UTC, jbcaron commented on crates/primitives/convert/src/felt.rs
> +    if !bytes.iter().take(12).all(|&b| b == 0) {
You’re right

2024-11-19 07:02 UTC, Trantorian1 commented
> how did we miss that when comparing what the starkware fgw and ours returns?

No specs :D

2024-11-19 07:04 UTC, Trantorian1 approved these changes
All good :+1:

2024-11-19 09:59 UTC, merged