fix(gateway): serialize `tip` as hex in UserTransaction
madara-alliance/madara pull request #436
Opened 2024-12-20 13:15 UTC by jbcaron

## Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix

## What is the current behavior?

Resolves: #NA

## What is the new behavior?

-

## Does this introduce a breaking change?

## Other information

2024-12-20 15:07 UTC, antiyro approved these changes

2025-01-09 16:59 UTC, cchudant commented on crates/madara/primitives/class/src/lib.rs
> +        let gzip_decoder = flate2::read::GzDecoder::new(base64_decoder);
aaaaaah
you should look at
https://github.com/madara-alliance/madara/pull/459

also I had no idea compressed sierra was a thing? i thought only legacy classes were compressed
that's new right?

2025-01-10 08:06 UTC, Trantorian1 requested changes

2025-01-10 08:06 UTC, Trantorian1 commented on CHANGELOG.md
> +- fix(gateway): serialize `tip` as hex in UserTransaction
Please remove this code since we now have a CI action for the changelog and this might interfere with other prs.

2025-01-10 08:06 UTC, Trantorian1 commented on crates/madara/client/gateway/server/src/handler.rs
> +    let tx: BroadcastedDeclareTxn<Felt> = tx.try_into().unwrap();
Where is this unwrap being checked? Could you please add a comment here specifying why this is safe?

2025-01-10 08:06 UTC, Trantorian1 commented on crates/madara/primitives/class/src/lib.rs
> +        drop(gzip_encoder);
Why the manual call to drop here?

2025-01-10 08:06 UTC, Trantorian1 commented on crates/madara/primitives/class/src/lib.rs
> +        let sierra_program = String::from_utf8(base64_encoder.into_inner()).unwrap();
Why is it safe to unwrap here?

2025-01-10 08:06 UTC, Trantorian1 commented on crates/madara/primitives/gateway/src/user_transaction.rs
> +//! //! # Important Note
```suggestion
//! # Important Note
```

2025-01-10 08:06 UTC, Trantorian1 commented on crates/madara/primitives/gateway/src/user_transaction.rs
> +//!
```suggestion
//! - [`UnsupportedQueryTransaction`]: When attempting to convert a query-only transaction
//! - [`ContractClassDecodeError`]: When contract class decoding fails
//!
//! [`UnsupportedQueryTransaction`]: UserTransactionConversionError::UnsupportedQueryTransaction
//! [`ContractClassDecodeError`]: UserTransactionConversionError::ContractClassDecodeError
```

2025-01-10 08:06 UTC, Trantorian1 commented on crates/madara/primitives/gateway/src/user_transaction.rs
> +//!
nitpick

2025-01-10 11:12 UTC, jbcaron commented on crates/madara/primitives/class/src/lib.rs
> +        drop(gzip_encoder);
The drop is needed to explicitly close the GZIP encoder before finalizing the base64 encoding, ensuring all compressed data is properly flushed and written to the underlying base64 encoder.

2025-01-10 11:18 UTC, jbcaron commented on crates/madara/primitives/class/src/lib.rs
> +        let sierra_program = String::from_utf8(base64_encoder.into_inner()).unwrap();
fixed

2025-01-10 11:19 UTC, jbcaron commented on crates/madara/client/gateway/server/src/handler.rs
> +    let tx: BroadcastedDeclareTxn<Felt> = tx.try_into().unwrap();
fixed

2025-01-14 07:53 UTC, Trantorian1 approved these changes

2025-01-14 07:53 UTC, Trantorian1 commented on crates/madara/primitives/gateway/src/user_transaction.rs
> +impl<T> ValidTransactionResult for AddDeployAccountTransactionResult<T> {}
Consider sealing this trait by either making it private if does not need to be accessed outside of this crate, or a sub-trait of a private trait if it does.

```suggestion
/// Ensures [ValidTransactionResult] is accessible from outside the crate but cannot be implemented on any new structs
trait Sealed {} 

/// Marker trait to restrict which types can be used as transaction results.
/// Only valid Starknet transaction responses implement this trait.
pub trait ValidTransactionResult: Sealed {}

// Implement the marker trait for the three valid transaction result types
impl<T> Sealed for AddInvokeTransactionResult<T> {}
impl<T> Sealed for AddDeclareTransactionResult<T> {}
impl<T> Sealed for AddDeployAccountTransactionResult<T> {}
impl<T> ValidTransactionResult for AddInvokeTransactionResult<T> {}
impl<T> ValidTransactionResult for AddDeclareTransactionResult<T> {}
impl<T> ValidTransactionResult for AddDeployAccountTransactionResult<T> {}
```

2025-01-15 13:31 UTC, merged