fix(block_time): block time can no longer be less than pending block update time
madara-alliance/madara pull request #447
Opened 2024-12-30 14:47 UTC by Trantorian1

# Pull Request type

- Bugfix

## What is the current behavior?

Block time can be less than pending block update time (also known as tick time). This is an issue as it means only empty blocks will be produced.

Resolves: #277 

## What is the new behavior?

Forbids the node from starting as a sequencer if ever its block time is less than its tick time.

## Does this introduce a breaking change?

No

2025-01-07 16:59 UTC, Mohiiit reviewed
lgtm, minor doubts

2025-01-07 16:59 UTC, Mohiiit commented on crates/madara/node/src/cli/chain_config_overrides.rs
this was required, thanks

2025-01-07 16:59 UTC, Mohiiit commented on crates/madara/node/src/main.rs
> +        anyhow::bail!("Block time");
if we just do panic!() that would be enough right? I mean the tracing::error is covering the message precisely, having Block time here doesn't add any value, wdyt? or we can do: 
```suggestion
        anyhow::bail!(
            "invalid block configuration: block time {} is less than pending update time {}", 
            config.block_time.as_secs(),
            config.pending_block_update_time.as_secs()
        );
```

2025-01-07 16:59 UTC, Mohiiit commented on crates/madara/node/src/main.rs
> +            anyhow::bail!("devnet");
same as above

2025-01-07 17:28 UTC, notlesh commented on crates/madara/node/src/cli/mod.rs
> +    #[allow(missing_docs)]
Was the previous comment wrong? It seems more useful than nothing...

2025-01-07 17:33 UTC, notlesh commented on CHANGELOG.md
> -- chore(nix): resolve flake and direnv compatibility issues
Is this intentional?

2025-01-07 17:40 UTC, notlesh commented on crates/madara/node/src/cli/chain_config_overrides.rs
> +    /// --chain-config-override=block_time=30s,pending_block_update_time=2s...
It would be good to mention here what the possible keys are, is there something you can reference about that?

2025-01-07 17:44 UTC, notlesh requested changes
Left a couple nits/questions, but also wanted to ask if `block time` and `bending block update time` are documented anywhere. I don't see them in `--help`.

`Tick time` was also confusing to me while reading through the PR/issue, is that a user-facing term? If not, no big deal.

2025-01-08 08:11 UTC, Trantorian1 commented on crates/madara/node/src/main.rs
> +        anyhow::bail!("Block time");
I don't like the use of `panic` as this feels like a correct execution path for the program and not something we should violently abort. The [rust docs](https://doc.rust-lang.org/std/macro.panic.html#when-to-use-panic-vs-result) are a bit unclear regarding this but I feel we shouldn't use it here. Switched the error message to just be `anyhow::bail` since our configuration of `tracing` should print to `stderr` anyway.

2025-01-08 08:12 UTC, Trantorian1 commented on crates/madara/node/src/main.rs
> +            anyhow::bail!("devnet");
This is being address in #448

2025-01-08 08:14 UTC, Trantorian1 commented on crates/madara/node/src/cli/mod.rs
> +    #[allow(missing_docs)]
These docs do not appear in clap due to the use of `#[clap(flatten)]`. Instead, the docs on `ChainConfigOverrideParams` are used which are more extensive. Still, adding those back.

2025-01-08 08:27 UTC, Mohiiit commented on crates/madara/node/src/main.rs
> +        anyhow::bail!("Block time");
I see, so you mean developers will be allowed to keep pending tick time > block time?

and yes I agree that we have the same error in the `tracing`, we don't need it in the `anyhow::bail`

2025-01-08 08:50 UTC, Trantorian1 commented on crates/madara/node/src/cli/chain_config_overrides.rs
> +    /// --chain-config-override=block_time=30s,pending_block_update_time=2s...
Added some more docs

2025-01-08 08:51 UTC, Trantorian1 commented
> Left a couple nits/questions, but also wanted to ask if `block time` and `bending block update time` are documented anywhere. I don't see them in `--help`.
> 
> `Tick time` was also confusing to me while reading through the PR/issue, is that a user-facing term? If not, no big deal.

Yep, this was pretty confusing to me too when I started work on this PR. I have added docs to all of this into the CLI. Hopefully this makes this part of the code a bit clearer.

2025-01-08 09:20 UTC, Trantorian1 commented on crates/madara/node/src/main.rs
> +        anyhow::bail!("Block time");
Yes, well more specifically developers will be _required_ to keep tick time >= block time?

2025-01-08 09:29 UTC, Mohiiit commented on crates/madara/node/src/main.rs
> +        anyhow::bail!("Block time");
you mean block time >= tick time?

2025-01-08 09:30 UTC, Trantorian1 commented on crates/madara/node/src/main.rs
> +        anyhow::bail!("Block time");
Oh yes sorry XD

2025-01-08 15:41 UTC, notlesh approved these changes

2025-01-08 15:42 UTC, Mohiiit approved these changes

2025-01-09 09:45 UTC, merged