Fix/proposer factory
madara-alliance/madara pull request #80
Opened 2024-04-26 14:20 UTC by antiyro

removing unecessary config and concensus from substrate

2024-04-26 22:50 UTC, jbcaron requested changes
refer to comments

2024-04-26 22:50 UTC, jbcaron commented on crates/client/db/src/lib.rs
> +//! A database backend storing data about deoxys chain
starknet chain

2024-04-26 22:50 UTC, jbcaron commented on crates/client/rpc/src/methods/read/estimate_fee.rs
> +			// FIXME: https://github.com/kasarlabs/deoxys/issues/329
issue does not match

2024-04-26 22:50 UTC, jbcaron commented on crates/node/src/commands/run.rs
> -        log::debug!("Using fetch block config: {:?}", fetch_block_config);
debug can be helpful

2024-04-26 22:50 UTC, jbcaron commented on crates/primitives/convert/src/contract.rs
> +        sierra_program: vec![], // FIXME: https://github.com/kasarlabs/deoxys/issues/775
issue does not match

2024-04-26 22:50 UTC, jbcaron commented on crates/runtime/src/pallets.rs
> +// You can also follow this issue on github: https://github.com/kasarlabs/deoxys/issues/83
issue does not match

2024-04-29 09:28 UTC, jbcaron approved these changes

2024-04-29 09:42 UTC, Trantorian1 approved these changes

2024-04-29 10:17 UTC, merged